/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Faq = {
  _id: string;
  _type: 'faq';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  list?: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }>;
};

export type Income = {
  _id: string;
  _type: 'income';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
};

export type Cupon = {
  _id: string;
  _type: 'cupon';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  code?: string;
  startDate?: string;
  endDate?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
      _key: string;
    }
>;

export type Color = {
  _id: string;
  _type: 'color';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type Product = {
  _id: string;
  _type: 'product';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  price?: number;
  brand?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'brand';
  };
  category?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'category';
  };
  dateAdded?: string;
  isFeatured?: boolean;
  mainImages?: Array<{
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'mainImage';
    _key: string;
  }>;
  desc?: BlockContent;
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  desc?: string;
};

export type Brand = {
  _id: string;
  _type: 'brand';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | Faq
  | Income
  | Cupon
  | BlockContent
  | Color
  | Product
  | Category
  | Brand
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: PRODUCTS_QUERY
// Query: *[_type == 'product'    && defined(slug.current)]    |order(dateAdded desc){        name,        slug,        price,        desc,        'category': category->{name},        "brand": brand->{name},        'image': {            'urls': mainImages[].asset->url,            'alts': mainImages[].alt        },        isFeatured    }
export type PRODUCTS_QUERYResult = Array<{
  name: string | null;
  slug: Slug | null;
  price: number | null;
  desc: BlockContent | null;
  category: {
    name: string | null;
  } | null;
  brand: {
    name: string | null;
  } | null;
  image: {
    urls: Array<string | null> | null;
    alts: Array<string | null> | null;
  };
  isFeatured: boolean | null;
}>;
// Variable: BRANDS_QUERY
// Query: *[_type == 'brand'    && defined(slug.current)]{        name,        'imageURL': mainImage.asset->{url},        'imageALT': mainImage.alt        }
export type BRANDS_QUERYResult = Array<{
  name: string | null;
  imageURL: {
    url: string | null;
  } | null;
  imageALT: string | null;
}>;
// Variable: CATEGORIES_QUERY
// Query: *[_type == 'category'    && defined(slug.current)]    |order(name asc){        name,        slug    }
export type CATEGORIES_QUERYResult = Array<{
  name: string | null;
  slug: Slug | null;
}>;
// Variable: FAQS_QUERY
// Query: *[_type == 'faq'    && defined(slug.current)]{        list[]{            question,            answer        }    }
export type FAQS_QUERYResult = Array<{
  list: Array<{
    question: string | null;
    answer: string | null;
  }> | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    "\n    *[_type == 'product'\n    && defined(slug.current)]\n    |order(dateAdded desc){\n        name,\n        slug,\n        price,\n        desc,\n        'category': category->{name},\n        \"brand\": brand->{name},\n        'image': {\n            'urls': mainImages[].asset->url,\n            'alts': mainImages[].alt\n        },\n        isFeatured\n    }\n": PRODUCTS_QUERYResult;
    "\n    *[_type == 'brand'\n    && defined(slug.current)]{\n        name,\n        'imageURL': mainImage.asset->{url},\n        'imageALT': mainImage.alt\n        }": BRANDS_QUERYResult;
    "\n    *[_type == 'category'\n    && defined(slug.current)]\n    |order(name asc){\n        name,\n        slug\n    }\n    ": CATEGORIES_QUERYResult;
    "\n    *[_type == 'faq'\n    && defined(slug.current)]{\n        list[]{\n            question,\n            answer\n        }\n    }\n ": FAQS_QUERYResult;
  }
}
